# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part2', '0005_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=30)),
            ],
        ),
    ]
